language: objective-c
xcode_workspace: savings-assistant.xcworkspace
xcode_scheme: savings-assistant
osx_image: xcode6.4
xcode_sdk: iphonesimulator8.4

before_install: gem install cocoapods -v '=0.38.2'
